name: NeyGin_Core
version: 2.0.2
author: Neyuux_
main: fr.neyuux.neygincore.Core
depend: [LG, PvPKits, UHC, Tournoi]
commands:
  game:
    description: Modifie le jeu actuel
    aliases: [g]
  sondage:
    description: Effectue un sondage
    aliases: [sond, sdg, sd]
  updateitems:
    description: Mets a jour tous les items du joueur
  end:
    description: Reset la map actuelle
    permission: end.use
  spec:
    description: Commande spectateur pour la map actuelle
    aliases: [s, spectateur, sp, spectateurs, spect]
  tell:
    description: Envoie un message
    aliases: [msg, message, m, whisper, wh, whp, envoyerunmessageaquelquun]
  broadcast:
    description: Fais une annonce
    permission: broadcast.use
    aliases: [bd, bc, b, annonce, announce, ann]
  start:
    description: Demarre la partie
    aliases: [st, run]
    permission: start.use
  respond:
    description: Repondre a un message
    aliases: [r, repond, repondre, rep]
  tournamentconnexion:
    description : Demarre le plugin tournoi pour une inscription
  invsee:
    description: Regarder l'inventaire de quelqu'un
    aliases:
      - seeinv
      - checkinv
    permission: invsee.use